name: Lint
on: [ push, pull_request ]
permissions:
  contents: read
jobs:
  rust:
    name: Cargo clippy & fmt
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
      with:
        egress-policy: block
        allowed-endpoints: >
          azure.archive.ubuntu.com:80
          crates.io:443
          esm.ubuntu.com:443
          github.com:443
          index.crates.io:443
          motd.ubuntu.com:443
          ppa.launchpadcontent.net:443
          static.crates.io:443
          static.rust-lang.org:443

    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Setup Rust toolchain
      run: rustup show && rustup update
    - name: cargo fmt
      run: cargo fmt -- --check
    - name: cargo clippy
      run: cargo clippy --all-features --tests -- -D warnings

  audit:
    name: Cargo Audit
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            crates.io:443
            github.com:443
            index.crates.io:443
            static.crates.io:443

      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install Cargo Audit
        run: cargo install cargo-audit

      - name: Run Cargo Audit
        run: cargo audit

  hack:
    name: Cargo Hack
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            crates.io:443
            github.com:443
            index.crates.io:443
            objects.githubusercontent.com:443
            static.crates.io:443

      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install Cargo Hack
        uses: taiki-e/install-action@3aeb53dd041c652ad28c1714cb9a10a4fbde32ff # cargo-hack

      - name: Run Cargo Hack
        run: cargo hack check --each-feature --no-dev-deps
