name: Test
on: [ push, pull_request ]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: block
          allowed-endpoints: >
            azure.archive.ubuntu.com:80
            crates.io:443
            esm.ubuntu.com:443
            github.com:443
            index.crates.io:443
            motd.ubuntu.com:443
            ppa.launchpadcontent.net:443
            static.crates.io:443
            static.rust-lang.org:443

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Update Rust toolchain
        run: rustup update
      - name: Build
        run: cargo build
      - name: Test
        run: |
          cargo test -- --nocapture --test-threads=1
          cargo test features=tracing
          cargo test --release --features=release -- --nocapture --test-threads=1
          cargo test --release -- --nocapture --test-threads=1
